@startuml

Instrumento <|-- Guitarra
Instrumento <|-- Saxo
Instrumento <|-- Tiple

Musico *-- Instrumento
Banda *-- Musico

Instrumento : afinar()
Instrumento : tocar()

Musico : Instrumento
Musico : afinar_instrumento()
Musico : tocar_instrumento()

Banda : instrumento()
Banda : afinar()
Banda : tocar()
Banda : armar_banda()

@enduml